"""Add vaccination days to model.

Revision ID: 064168ed1e13
Revises: 55c1273995b2
Create Date: 2021-01-28 16:43:23.412095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064168ed1e13'
down_revision = '55c1273995b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccination_day',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('open', sa.Boolean(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['vaccination_place.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccination_day')
    # ### end Alembic commands ###
