"""Add last notification time to subscriptions.

Revision ID: 2ee6fc8e1b2b
Revises: 064168ed1e13
Create Date: 2021-01-28 17:38:29.605315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ee6fc8e1b2b'
down_revision = '064168ed1e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_subscription', sa.Column('last_notification_at', sa.DateTime(), nullable=True))
    op.add_column('spot_subscription', sa.Column('last_notification_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot_subscription', 'last_notification_at')
    op.drop_column('group_subscription', 'last_notification_at')
    # ### end Alembic commands ###
