"""Add cities to stats.

Revision ID: 2f60d8e3a391
Revises: 0d462b556039
Create Date: 2021-02-20 14:03:52.459491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f60d8e3a391'
down_revision = '0d462b556039'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccination_stats', sa.Column('online_cities', sa.Integer(), nullable=True))
    op.add_column('vaccination_stats', sa.Column('total_cities', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccination_stats', 'total_cities')
    op.drop_column('vaccination_stats', 'online_cities')
    # ### end Alembic commands ###
