"""Add push_sub to subscriptions.

Revision ID: 3cbf6f088fd0
Revises: c618aba4c9f4
Create Date: 2021-02-07 21:12:31.547135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cbf6f088fd0'
down_revision = 'c618aba4c9f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_subscription', sa.Column('push_sub', sa.Text(), nullable=True))
    op.add_column('spot_subscription', sa.Column('push_sub', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot_subscription', 'push_sub')
    op.drop_column('group_subscription', 'push_sub')
    # ### end Alembic commands ###
