"""Add free column to places.

Revision ID: 55c1273995b2
Revises: a15205961c8c
Create Date: 2021-01-27 16:33:37.269175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55c1273995b2'
down_revision = 'a15205961c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vaccination_place', sa.Column('free', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vaccination_place', 'free')
    # ### end Alembic commands ###
