"""Add created_at to subscriptions.

Revision ID: 9caa6a22ed8a
Revises: c15f213db125
Create Date: 2021-02-02 16:20:54.688907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caa6a22ed8a'
down_revision = 'c15f213db125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_subscription', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE group_subscription SET created_at = datetime('now', 'localtime')")
    op.add_column('spot_subscription', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.execute("UPDATE spot_subscription SET created_at = datetime('now', 'localtime')")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot_subscription', 'created_at')
    op.drop_column('group_subscription', 'created_at')
    # ### end Alembic commands ###
