"""Initial migration.

Revision ID: a15205961c8c
Revises: 
Create Date: 2021-01-27 15:32:06.458852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15205961c8c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eligibility_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=16), nullable=True),
    sa.Column('item_description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('secret', sa.LargeBinary(length=16), nullable=True),
    sa.Column('status', sa.Enum('UNCONFIRMED', 'CONFIRMED', name='status'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spot_subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('secret', sa.LargeBinary(length=16), nullable=True),
    sa.Column('status', sa.Enum('UNCONFIRMED', 'CONFIRMED', name='status'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccination_place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nczi_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('street_name', sa.String(length=64), nullable=True),
    sa.Column('street_number', sa.String(length=64), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_map',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['eligibility_group.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['group_subscription.id'], ),
    sa.PrimaryKeyConstraint('subscription_id', 'group_id')
    )
    op.create_table('places_map',
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['vaccination_place.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['spot_subscription.id'], ),
    sa.PrimaryKeyConstraint('subscription_id', 'place_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('places_map')
    op.drop_table('group_map')
    op.drop_table('vaccination_place')
    op.drop_table('spot_subscription')
    op.drop_table('group_subscription')
    op.drop_table('eligibility_group')
    # ### end Alembic commands ###
