"""Split push sub into endpoint.

Revision ID: a6464386756e
Revises: 3cbf6f088fd0
Create Date: 2021-02-09 17:45:41.778942

"""
import json

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6464386756e'
down_revision = '3cbf6f088fd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    op.add_column('group_subscription', sa.Column('push_sub_endpoint', sa.String(length=1024), nullable=True))
    group_pushes = list(conn.execute("SELECT id, push_sub FROM group_subscription;"))
    for id, push_sub in group_pushes:
        if push_sub:
            endpoint = json.loads(push_sub)["endpoint"]
            op.execute(f"UPDATE group_subscription SET push_sub_endpoint = '{endpoint}' WHERE id = {id}")

    op.add_column('spot_subscription', sa.Column('push_sub_endpoint', sa.String(length=1024), nullable=True))
    spot_pushes = list(conn.execute("SELECT id, push_sub FROM spot_subscription;"))
    for id, push_sub in spot_pushes:
        if push_sub:
            endpoint = json.loads(push_sub)["endpoint"]
            op.execute(f"UPDATE spot_subscription SET push_sub_endpoint = '{endpoint}' WHERE id = {id}")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spot_subscription', 'push_sub_endpoint')
    op.drop_column('group_subscription', 'push_sub_endpoint')
    # ### end Alembic commands ###
