"""Add stats table.

Revision ID: c15f213db125
Revises: 2ee6fc8e1b2b
Create Date: 2021-01-28 21:25:54.524992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15f213db125'
down_revision = '2ee6fc8e1b2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccination_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('total_free_spots', sa.Integer(), nullable=True),
    sa.Column('total_free_online_spots', sa.Integer(), nullable=True),
    sa.Column('online_places', sa.Integer(), nullable=True),
    sa.Column('total_places', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccination_stats')
    # ### end Alembic commands ###
