"""Add subscription stats.

Revision ID: c618aba4c9f4
Revises: edf7c598cec7
Create Date: 2021-02-05 18:59:21.112237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c618aba4c9f4'
down_revision = 'edf7c598cec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('unique_emails', sa.Integer(), nullable=True),
    sa.Column('shared_emails', sa.Integer(), nullable=True),
    sa.Column('spot_subs_top_id', sa.Integer(), nullable=True),
    sa.Column('spot_subs_confirmed', sa.Integer(), nullable=True),
    sa.Column('spot_subs_unconfirmed', sa.Integer(), nullable=True),
    sa.Column('group_subs_top_id', sa.Integer(), nullable=True),
    sa.Column('group_subs_confirmed', sa.Integer(), nullable=True),
    sa.Column('group_subs_unconfirmed', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscription_stats')
    # ### end Alembic commands ###
