"""Add user feedback.

Revision ID: cdd62a4e9a05
Revises: 2f60d8e3a391
Create Date: 2021-02-20 18:42:36.704219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdd62a4e9a05'
down_revision = '2f60d8e3a391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.LargeBinary(length=16), nullable=True),
    sa.Column('given', sa.Boolean(), nullable=True),
    sa.Column('reasons', sa.String(length=128), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_feedback')
    # ### end Alembic commands ###
